In [ ]:
pip install oracledb

In [14]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.39)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [20]:
import oracledb
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [19]:
# max row and columns to display
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)

# width of DataFrame
pd.set_option("display.width", 1000)

# Float number formatting
pd.options.display.float_format = "{:,.2f}".format

In [ ]:
conn = oracledb.connect(
    user="system",
    password="*****",
    dsn="127.0.0.1:1521/ORCLPDB"
)

In [30]:
# CREATE CONNECTION
user_name = "system"
password = "****"
host = "127.0.0.1" # localhost
port = "1521/"
service_name = "ORCLPDB" # service name for the databse we are accessing

conn = oracledb.connect(
    user="system",
    password=password,
    dsn=host+":"+port+service_name
)

In [24]:
cust_df = pd.read_sql(
    "SELECT * FROM CUSTOMER_INFO",
    conn
)

cust_df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_22240\3398522436.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cust_df = pd.read_sql(

   CUSTOMER_ID   SURNAME  CREDIT_SCORE GEOGRAPHY  GENDER   AGE  TENURE ESTIMATED_SALARY
0     15634602  Hargrave           619       FRA  Female 42.00       2     € 101,348.88
1     15647311      Hill           608     Spain  Female 41.00       1     € 112,542.58
2     15619304      Onio           502    French  Female 42.00       8     € 113,931.57
3     15701354      Boni           699       FRA  Female 39.00       1      € 93,826.63
4     15737888  Mitchell           850     Spain  Female 43.00       2      € 79,084.10

In [32]:
# CREATE CONNECTION WITH ANOTHER METHOD (SQL ALCHEMY)
user_name = "system"
password = "****"
host = "127.0.0.1" # localhost
port = "1521/"
service_name = "ORCLPDB" # service name for the databse we are accessing

engine = create_engine(
    "oracle+oracledb://"+user_name+":"+password+"@"+host+":"+port+"?service_name="+service_name
)

df = pd.read_sql("SELECT * FROM CUSTOMER_INFO", engine)
df

       customer_id    surname  credit_score geography  gender   age  tenure estimated_salary
0         15634602   Hargrave           619       FRA  Female 42.00       2     € 101,348.88
1         15647311       Hill           608     Spain  Female 41.00       1     € 112,542.58
2         15619304       Onio           502    French  Female 42.00       8     € 113,931.57
3         15701354       Boni           699       FRA  Female 39.00       1      € 93,826.63
4         15737888   Mitchell           850     Spain  Female 43.00       2      € 79,084.10
...            ...        ...           ...       ...     ...   ...     ...              ...
9996      15569892  Johnstone           516    French    Male 35.00      10     € 101,699.77
9997      15584532        Liu           709       FRA  Female 36.00       7      € 42,085.58
9998      15682355  Sabbatini           772   Germany    Male 42.00       3      € 92,888.52
9999      15628319     Walker           792    French  Female 28.00       4      € 38,190.78
10000     15628319     Walker           792    French  Female 28.00       4      € 38,190.78

[10001 rows x 8 columns]